name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    env:
      PORT: "3000"
      DATABASE_URL: "postgresql://postgres:MyPassword%23135@localhost:5432/project01_test?schema=public"
      JWT_SECRET: "test-secret"
      JWT_EXPIRES_IN: "15m"
      REFRESH_TOKEN_SECRET: "test-refresh-secret"
      FRONTEND_URL: "http://localhost:5173"
      REFRESH_TOKEN_EXPIRES_DAYS: "7"
      BCRYPT_SALT_ROUNDS: "10"
      NODE_ENV: "test"

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: "MyPassword#135"
          POSTGRES_DB: project01_test

        ports:
          - 5432:5432

        options: >-
          --health-cmd="pg_isready -U postgres -d project01_test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate --config ./prisma.config.ts

      - name: Debug PostgreSQL
        run: |
          echo "=== ENV ==="
          echo "$DATABASE_URL"

          echo "=== WAITING FOR POSTGRES ==="
          for i in {1..30}; do
            pg_isready -h localhost -p 5432 -U postgres && break
            echo "Waiting for postgres..."
            sleep 2
          done

          echo "=== FINAL CHECK ==="
          pg_isready -h localhost -p 5432 -U postgres

      - name: Run database migrations
        run: npx prisma migrate deploy --config ./prisma.config.ts

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test